### PR TITLE
Updated to 1.0

### PR DESCRIPTION
**Pull request by Jdalt40**
Recompiled and fixed DLL errors, fixed XML as well.

### CODE REVIEW

**Comment by JonnyNova** [comment]
Can you revert the change of switching `Vector3` to `Vector2`? They are handled in 3d to allow for combat extended support.
For the removed messaging about SkyFallers, we decided to put those in there since there really isn't any feedback that the shields are taking massively damage and they are rare events. Can you make a case why they are better out?

**Comment by Jdalt40** [comment]
Hey JonnyNova, I’ll see what I can do when I get home about it, and I’ll try to revert back it to vector 3d when I get on. 

Have a good day :)

**Comment by Jdalt40** [comment]
Hey JonnyNova, just got that done, hopefully everything works fine ;)

**Comment by JonnyNova** [comment]
Thanks! I needed to manually separate some stuff so I created 5d9fd55 with your authorship information for this.

**Comment by Jdalt40** [comment]
All good, have a great day!

**Pull request closed without merging**
